// src/data/mockData.js

export const mockData = [
  {
    id: 'usm-001',
    title: 'Desarrollo de módulo CRM para gestión de contactos utilizando React y Supabase bajo metodología Scrum',
    author: 'Carlos Mendoza',
    faculty: 'Ingeniería',
    type: 'Tesis',
    date: '2026-02-10',
    excerpt: 'Propuesta arquitectónica y desarrollo de un sistema de gestión de relaciones con clientes (CRM) enfocado en la alta disponibilidad y escalabilidad, utilizando componentes funcionales y bases de datos en tiempo real.',
    readTime: '15 min',
    fileUrl: null,
    fileType: null,
    fileName: null,
  },
  {
    id: 'usm-002',
    title: 'Acto de Grado - Promoción LIX',
    author: 'Dirección de Control de Estudios',
    faculty: 'Todas',
    type: 'Evento',
    date: '2026-03-15',
    excerpt: 'Invitamos a toda la comunidad Usemista a celebrar el acto de grado de las facultades de FACES, Derecho e Ingeniería en la Plaza Central. Asistencia con traje formal.',
    location: 'Sede La Florencia - Plaza Central',
    fileUrl: 'https://www.w3.org/WAI/WCAG21/Techniques/pdf/img/table-word.jpg',
    fileType: 'image',
    fileName: 'invitacion-grado.jpg',
  },
  {
    id: 'usm-003',
    title: 'Impacto de la Inteligencia Artificial en la salud mental de adultos jóvenes: Un enfoque psicológico',
    author: 'Dra. Elena Villalobos',
    faculty: 'FACES',
    type: 'Artículo',
    date: '2026-02-08',
    excerpt: 'Análisis clínico sobre la interacción de los jóvenes con perfiles y sistemas de IA, evaluando los efectos en la ansiedad social y el desarrollo de la identidad durante la etapa universitaria.',
    readTime: '8 min',
    fileUrl: null,
    fileType: null,
    fileName: null,
  },
  {
    id: 'usm-004',
    title: 'Implementación de aplicaciones móviles multiplataforma con Flutter para la gestión universitaria',
    author: 'Luis Hernández',
    faculty: 'Ingeniería',
    type: 'Tesis',
    date: '2026-01-25',
    excerpt: 'Estudio sobre la optimización de tiempos de desarrollo al crear archivos APK y compilaciones iOS desde un mismo código base para digitalizar procesos administrativos.',
    readTime: '12 min',
    fileUrl: null,
    fileType: 'pdf',
    fileName: 'tesis-flutter-usm.pdf',
  },
  {
    id: 'usm-005',
    title: 'Reformas al Código Orgánico Procesal Penal y su impacto en la fase preparatoria',
    author: 'Ana Carolina Rojas',
    faculty: 'Derecho',
    type: 'Tesis',
    date: '2025-11-20',
    excerpt: 'Investigación documental sobre las recientes modificaciones legislativas y cómo afectan los lapsos procesales para la defensa en el sistema judicial venezolano.',
    readTime: '20 min',
    fileUrl: null,
    fileType: null,
    fileName: null,
  },
  {
    id: 'usm-006',
    title: 'Jornada de Actualización Odontológica',
    author: 'Facultad de Odontología',
    faculty: 'Odontología',
    type: 'Evento',
    date: '2026-02-28',
    excerpt: 'Seminario práctico sobre nuevos biomateriales en endodoncia y restauraciones estéticas. Contará con la participación de especialistas invitados.',
    location: 'Auditorio Clínica Odontológica USM',
    fileUrl: null,
    fileType: null,
    fileName: null,
  },
  {
    id: 'usm-007',
    title: 'Estrategias de Marketing Digital para PyMES en el sector farmacéutico',
    author: 'Sofía Castillo',
    faculty: 'Farmacia',
    type: 'Resumen',
    date: '2026-02-05',
    excerpt: 'Resumen del capítulo 4: Cómo las farmacias locales pueden utilizar redes sociales y sistemas ágiles para mejorar la atención y fidelización del paciente.',
    readTime: '5 min',
    fileUrl: null,
    fileType: null,
    fileName: null,
  },
  {
    id: 'usm-008',
    title: 'Defensa Pública de Tesis: Arquitectura Sostenible',
    author: 'Coordinación de Arquitectura',
    faculty: 'Ingeniería',
    type: 'Evento',
    date: '2026-02-20',
    excerpt: 'Defensa pública del proyecto de grado sobre diseño de viviendas bioclimáticas para el clima tropical de Caracas.',
    location: 'Salón de Usos Múltiples - Edificio de Ingeniería',
    fileUrl: null,
    fileType: 'video',
    fileName: 'transmision-defensa.mp4',
  }
];

export const faculties = ['Todas', 'Derecho', 'Ingeniería', 'FACES', 'Farmacia', 'Odontología'];
export const contentTypes = ['Todos', 'Tesis', 'Artículo', 'Evento', 'Resumen'];