// src/data/mockData.js

export const mockData = [
  {
    id: 'usm-001',
    title: 'Reformas al Código Orgánico Procesal Penal y su impacto en la fase preparatoria',
    author: 'Ana Carolina Rojas',
    school: 'Derecho',
    type: 'Tesis',
    date: '2026-02-10',
    excerpt: 'Investigación documental sobre las recientes modificaciones legislativas y cómo afectan los lapsos procesales para la defensa en el sistema judicial venezolano.',
    readTime: '20 min',
    fileUrl: null,
    fileType: null,
    fileName: null,
  },
  {
    id: 'usm-002',
    title: 'Acto de Grado - Promoción LIX',
    author: 'Dirección de Control de Estudios',
    school: 'Todas',
    type: 'Evento',
    date: '2026-03-15',
    excerpt: 'Invitamos a toda la comunidad Usemista a celebrar el acto de grado de la Facultad de Derecho en la Plaza Central. Asistencia con traje formal.',
    location: 'Sede La Florencia - Plaza Central',
    fileUrl: 'https://www.w3.org/WAI/WCAG21/Techniques/pdf/img/table-word.jpg',
    fileType: 'image',
    fileName: 'invitacion-grado.jpg',
  },
  {
    id: 'usm-003',
    title: 'Análisis del Derecho Internacional Humanitario en conflictos contemporáneos',
    author: 'Dr. Ricardo Paredes',
    school: 'Estudios Internacionales',
    type: 'Artículo',
    date: '2026-02-08',
    excerpt: 'Estudio sobre la aplicación del DIH en los conflictos armados del siglo XXI y los desafíos para la protección de civiles en contextos de guerra asimétrica.',
    readTime: '8 min',
    fileUrl: null,
    fileType: null,
    fileName: null,
  },
  {
    id: 'usm-004',
    title: 'La mediación como mecanismo alternativo de resolución de conflictos en Venezuela',
    author: 'Luis Hernández',
    school: 'Derecho',
    type: 'Tesis',
    date: '2026-01-25',
    excerpt: 'Estudio sobre la eficacia de la mediación en el sistema judicial venezolano y su impacto en la descongestión de tribunales civiles y mercantiles.',
    readTime: '12 min',
    fileUrl: null,
    fileType: 'pdf',
    fileName: 'tesis-mediacion-usm.pdf',
  },
  {
    id: 'usm-005',
    title: 'Política exterior venezolana y sus relaciones con organismos multilaterales',
    author: 'María Fernanda López',
    school: 'Estudios Internacionales',
    type: 'Tesis',
    date: '2025-11-20',
    excerpt: 'Análisis de la participación de Venezuela en la ONU, OEA y CELAC durante el período 2020-2025, evaluando el cumplimiento de compromisos internacionales.',
    readTime: '15 min',
    fileUrl: null,
    fileType: null,
    fileName: null,
  },
  {
    id: 'usm-006',
    title: 'Jornada de Actualización en Derecho Constitucional',
    author: 'Escuela de Derecho',
    school: 'Derecho',
    type: 'Evento',
    date: '2026-02-28',
    excerpt: 'Seminario sobre las recientes interpretaciones constitucionales y su impacto en los derechos fundamentales. Contará con la participación de magistrados invitados.',
    location: 'Auditorio Facultad de Derecho USM',
    fileUrl: null,
    fileType: null,
    fileName: null,
  },
  {
    id: 'usm-007',
    title: 'El rol de la diplomacia digital en las relaciones internacionales modernas',
    author: 'Sofía Castillo',
    school: 'Estudios Internacionales',
    type: 'Resumen',
    date: '2026-02-05',
    excerpt: 'Resumen del capítulo 4: Cómo las redes sociales y plataformas digitales están transformando la práctica diplomática y la comunicación entre Estados.',
    readTime: '5 min',
    fileUrl: null,
    fileType: null,
    fileName: null,
  },
  {
    id: 'usm-008',
    title: 'Defensa Pública de Tesis: Derecho Ambiental Comparado',
    author: 'Coordinación de Derecho',
    school: 'Derecho',
    type: 'Evento',
    date: '2026-02-20',
    excerpt: 'Defensa pública del proyecto de grado sobre legislación ambiental comparada entre Venezuela y Colombia.',
    location: 'Salón de Usos Múltiples - Facultad de Derecho',
    fileUrl: null,
    fileType: 'video',
    fileName: 'transmision-defensa.mp4',
  }
];

export const schools = ['Todas', 'Derecho', 'Estudios Internacionales'];
export const contentTypes = ['Todos', 'Tesis', 'Artículo', 'Evento', 'Resumen'];